"""Init migration 2

Revision ID: 86c6d325745d
Revises: 46b7de44401e
Create Date: 2025-03-29 17:16:26.293074

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86c6d325745d"
down_revision: Union[str, None] = "46b7de44401e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("files_user_id_idx", table_name="files")
    op.create_foreign_key(
        op.f("files_user_id_fkey"),
        "files",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("files_user_id_fkey"), "files", type_="foreignkey")
    op.create_index("files_user_id_idx", "files", ["user_id"], unique=False)
    # ### end Alembic commands ###
